[versions]
agp = "8.11.2"
arrowBom = "2.2.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.5"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.1"
junit = "4.13.2"
kotlin = "2.2.21"
ktor = "3.3.1"
logback = "1.5.20"
sqldelight = "2.0.2"
kotlinx-serialization = "1.8.0"
kotlinx-coroutines = "1.10.1"
kotlinx-datetime = "0.6.1"
ksp = "2.2.21-2.0.4"
androidxComposeFoundation = "1.8.0-alpha07"
koinBom = "4.1.0"

[libraries]
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-android-compat = { group = "io.insert-koin", name = "koin-android-compat" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koin-test = { group = "io.insert-koin", name = "koin-test" }

arrow-bom = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrowBom" }
arrow-annotations = { group = "io.arrow-kt", name = "arrow-annotations" }
arrow-atomic = { group = "io.arrow-kt", name = "arrow-atomic" }
arrow-autoclose = { group = "io.arrow-kt", name = "arrow-autoclose" }
arrow-cache4k = { group = "io.arrow-kt", name = "arrow-cache4k" }
arrow-collectors = { group = "io.arrow-kt", name = "arrow-collectors" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core" }
arrow-functions = { group = "io.arrow-kt", name = "arrow-functions" }
arrow-core-high-arity = { group = "io.arrow-kt", name = "arrow-core-high-arity" }
arrow-core-retrofit = { group = "io.arrow-kt", name = "arrow-core-retrofit" }
arrow-core-serialization = { group = "io.arrow-kt", name = "arrow-core-serialization" }
arrow-eval = { group = "io.arrow-kt", name = "arrow-eval" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines" }
arrow-fx-stm = { group = "io.arrow-kt", name = "arrow-fx-stm" }
arrow-optics = { group = "io.arrow-kt", name = "arrow-optics" }
arrow-optics-compose = { group = "io.arrow-kt", name = "arrow-optics-compose" }
arrow-optics-reflect = { group = "io.arrow-kt", name = "arrow-optics-reflect" }
arrow-resilience = { group = "io.arrow-kt", name = "arrow-resilience" }
arrow-suspendapp = { group = "io.arrow-kt", name = "suspendapp", version = "0.4.0" }
arrow-ksp = { group = "io.arrow-kt", name = "arrow-optics-ksp-plugin", version.ref = "arrowBom" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxComposeFoundation" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }


kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-serverContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-jsonSerialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-websocket = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }

sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-js = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqldelight" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
